# This database config file must be kept within one of the following paths, relative to
# the file attempting to make the database connection:
# "", "./config", "/config", "../", "../config", "../..", "../../config", "APP_PATH", "POP_PATH"
# For more information: https://github.com/gobuffalo/pop/blob/master/config.go

# This file must be kept in the same directory as the main file being run. Otherwise, the database
# will not be found when the program is run.
# To meet the requirements above (line 3), $APP_PATH is explicitly defined in the docker-compose.yml file.

development:
  dialect: postgres
  database: consents_development
  user: {{envOr "POSTGRES_USER" "postgres"}}
  password: {{envOr "POSTGRES_PASSWORD" "postgres"}}
  host: consents-database
  port: 5432
  pool: 5

# Checks TEST_DATABASE_URL first, then defaults to shown URL if necessary
#test:
#  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/gms_test?sslmode=disable"}}

# Checks DATABASE_URL first, then defaults to shown URL if necessary
#production:
#  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/gms_production?sslmode=disable"}}
